### ISSUE TITLE
thread 'main' panicked at 'Approve transaction failed', src/main.rs:124:14

### ISSUE THREAD

**Issue by DiMiTriFrog** [azerpas/uniswap-cli#12]
When i'm trying to run on Polygon i'm having this output when tries to Approve:

```
thread 'main' panicked at 'Approve transaction failed', src/main.rs:124:14
stack backtrace:
   0:        0x10c487a83 - std::backtrace_rs::backtrace::libunwind::trace::h14243dc752b5beac
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x10c487a83 - std::backtrace_rs::backtrace::trace_unsynchronized::h71ecb3a9455536a6
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10c487a83 - std::sys_common::backtrace::_print_fmt::h7e307467d6e88eaf
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x10c487a83 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he60192cdeae7ff98
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x10c4a939b - core::fmt::rt::Argument::fmt::hef24bdd6ecabdaa4
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/rt.rs:138:9
   5:        0x10c4a939b - core::fmt::write::hccf73e6ac9b102cd
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/mod.rs:1094:21
   6:        0x10c48439e - std::io::Write::write_fmt::h2da296a2a97aa10d
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/io/mod.rs:1714:15
   7:        0x10c48787a - std::sys_common::backtrace::_print::h57786acb50d0c08a
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x10c48787a - std::sys_common::backtrace::print::h57a90601b74ca1dc
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x10c488d55 - std::panicking::default_hook::{{closure}}::h8463146ca7fe4cbf
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:269:22
  10:        0x10c488aff - std::panicking::default_hook::h473c81bbe30d7761
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:288:9
  11:        0x10c4892b0 - std::panicking::rust_panic_with_hook::h0ff95e3e20549b0d
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:705:13
  12:        0x10c4891d3 - std::panicking::begin_panic_handler::{{closure}}::h5e967ae12a1d4ba1
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:597:13
  13:        0x10c487e89 - std::sys_common::backtrace::__rust_end_short_backtrace::h5c230463e113192d
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:151:18
  14:        0x10c488f0d - rust_begin_unwind
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
  15:        0x10c4c5533 - core::panicking::panic_fmt::h9d91d0e3e7a6cd1a
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
  16:        0x10c4c54fa - core::panicking::panic_display::he6a74fa9134260da
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:150:5
  17:        0x10c4c54fa - core::panicking::panic_str::hd69d90b586705e4c
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:134:5
  18:        0x10c4c54fa - core::option::expect_failed::h5507fdea4fa81077
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/option.rs:1952:5
  19:        0x10bb750ee - core::option::Option<T>::expect::h49f81d57b4785bce
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/option.rs:898:21
  20:        0x10bba5c5e - uniswap_cli::main::{{closure}}::h274e8280c3fb5e48
                               at /Users/Leopoldo/Downloads/bot/src/main.rs:119:46
  21:        0x10bb72b92 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::h641df56fbeb85f7c
                               at /Users/Leopoldo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  22:        0x10bb729c3 - tokio::runtime::coop::with_budget::hdd535cbd19192905
                               at /Users/Leopoldo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  23:        0x10bb729c3 - tokio::runtime::coop::budget::hc16e63eeca5e8d96
                               at /Users/Leopoldo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  24:        0x10bb729c3 - tokio::runtime::park::CachedParkThread::block_on::hb2facfd80d4139c3
                               at /Users/Leopoldo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  25:        0x10bb72dc0 - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::ha1eea6e85ccb3385
                               at /Users/Leopoldo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  26:        0x10bbc490f - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}::h318b7717ae475b61
                               at /Users/Leopoldo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  27:        0x10bb25723 - tokio::runtime::context::runtime::enter_runtime::h732bbfaf7f5616ed
                               at /Users/Leopoldo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  28:        0x10bbc48aa - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::hc88511a220e0f3d3
                               at /Users/Leopoldo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  29:        0x10bb77b6d - tokio::runtime::runtime::Runtime::block_on::heb21faf93d901498
                               at /Users/Leopoldo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:349:45
  30:        0x10bb40bbe - uniswap_cli::main::hc4f42dba0e75cec8
                               at /Users/Leopoldo/Downloads/bot/src/main.rs:194:5
  31:        0x10bb14a6e - core::ops::function::FnOnce::call_once::hd8dcecc31b06ceb8
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
  32:        0x10bb6b891 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf52f92d8c658de2d
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:135:18
  33:        0x10bb3bc64 - std::rt::lang_start::{{closure}}::hd41144753d07bd01
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:166:18
  34:        0x10c47e97a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h4945e40fadb4e102
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:284:13
  35:        0x10c47e97a - std::panicking::try::do_call::h3f89e890c35ee58d
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  36:        0x10c47e97a - std::panicking::try::hd7e13b924cbe36ec
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  37:        0x10c47e97a - std::panic::catch_unwind::h846dde69138eb551
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  38:        0x10c47e97a - std::rt::lang_start_internal::{{closure}}::h0db65befb440833b
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:48
  39:        0x10c47e97a - std::panicking::try::do_call::hf8ebe7d8efbefca2
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  40:        0x10c47e97a - std::panicking::try::hb7bf29765365750b
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  41:        0x10c47e97a - std::panic::catch_unwind::h49d9b5ea01685039
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  42:        0x10c47e97a - std::rt::lang_start_internal::hf7e13fcf609c9250
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:20
  43:        0x10bb3bc37 - std::rt::lang_start::hc8bf00c5f572515b
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:165:17
  44:        0x10bb45cb8 - _main
  45:     0x7ff80559a41f - <unknown>
```

**Comment by DiMiTriFrog** [comment]
I noticed that it only fails when attempting a write, but not a read. When executing a call() function it works perfectly, but when it is a send() function, this is when it fails.

**Comment by azerpas** [comment]
@DiMiTriFrog  Could you post your anonymised command args? :)
